# Generated by Django 2.1.4 on 2019-04-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRM', '0002_auto_20190430_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeExperience',
            new_name='ResourceExperience',
        ),
    ]
