# Generated by Django 2.1.4 on 2019-04-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRM', '0003_auto_20190430_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
