# Generated by Django 2.1.4 on 2019-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRM', '0006_auto_20190430_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='probability',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
    ]
