# Generated by Django 2.1 on 2019-05-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRM', '0008_projects_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='budgetHours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='createdDate',
            field=models.DateField(),
        ),
    ]
