from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(AllocationTypes)
admin.site.register(Teams)
admin.site.register(Countries)
admin.site.register(Disciplines)
admin.site.register(Roles)
admin.site.register(StatusTypes)
admin.site.register(Resources)
admin.site.register(ProjectStatusCategoryTypes)
admin.site.register(ProjectStatusTypes)
admin.site.register(Customers)
admin.site.register(Projects)
admin.site.register(ProductSkills)
admin.site.register(ResourceProductSkills)
admin.site.register(TechnicalGroup)
admin.site.register(TechnicalSkills)
admin.site.register(ResourceTechnicalSkills)
admin.site.register(ResourceExperience)
admin.site.register(TrainingType)
admin.site.register(ResourceTrainings)
admin.site.register(ResourceProjects)
admin.site.register(Locations)
admin.site.register(ProjectDemand)